# ==============================================================================
# simulate_auc_matrix() — General multivariate biomarker simulator
#
# Gaussian class-conditional core (v0.2 Milestone 1): parametrized
# correlation structures (user / exchangeable / ar1 / block), supplied-or-
# generated binary outcome, feasibility diagnostics with a nearest-PD
# fallback.
#
# Design note: biomarkers are drawn from MVN(mu_class, R) per outcome
# class, with mu_1 - mu_0 = delta (the binormal mean-shift, closed-form
# from the target AUC, exactly as in generate_data_analytical() and the
# `mean_shift` reported by simulate_auc_correlation()).  This is a
# class-conditional construction, not a thresholded latent-outcome
# construction: y is fixed (supplied or generated) BEFORE any biomarker is
# drawn, so supplied outcomes retain their exact values/order and
# generated outcomes get exact class counts in "exact" mode -- neither is
# achievable if the outcome is instead re-derived by thresholding a fresh
# latent draw.
#
# Non-normal marginals and perturbation modules (batch, outlier,
# MCAR/MAR/MNAR) are deferred to later milestones; see
# design/2026-07-21-aucmat-v0.2-design.md.
# ==============================================================================

#' Simulate a biomarker matrix with target AUCs and a parametrized
#' correlation structure
#'
#' Generates correlated biomarkers from a class-conditional multivariate
#' normal: `X | Y = 1 ~ MVN(mu_1, R)` and `X | Y = 0 ~ MVN(mu_0, R)`, with
#' the same p x p correlation matrix `R` in both classes and a per-biomarker
#' mean shift `mu_1 - mu_0` calibrated in closed form from `target_aucs`
#' (the equal-variance binormal relationship also used by
#' [generate_data_analytical()]).  `R` is built from a named structure
#' instead of requiring a hand-supplied matrix, and feasibility is reported
#' as structured diagnostics instead of a bare warning.
#'
#' Exactly one of (`y`, `positive`) or (`n`, `prevalence`) must be supplied.
#' Supplying `y` retains its exact values, class counts, and row order.
#' Generating `n`/`prevalence` defaults to exact rounded class counts with
#' randomised row order (`outcome_mode = "exact"`); pass
#' `outcome_mode = "bernoulli"` for independent Bernoulli draws with random
#' class counts.  Because the outcome is fixed before any biomarker is
#' drawn, both modes deliver the outcome's class counts exactly -- no
#' biomarker is generated by thresholding a latent variable.
#'
#' @param n Number of observations (generated-outcome mode).
#' @param prevalence Proportion of positive class, in (0, 1)
#'   (generated-outcome mode).
#' @param y Binary outcome vector (supplied-outcome mode).  Accepted inputs
#'   are logical, numeric 0/1, factor, or character with exactly two
#'   non-missing classes.
#' @param positive Optional positive class label when `y` is a factor or
#'   character (supplied-outcome mode).
#' @param outcome_mode `"exact"` (default) or `"bernoulli"`.  Only used
#'   when generating `y` from `n`/`prevalence`.
#' @param target_aucs Numeric vector of target AUC values, each in (0, 1).
#' @param correlation For `structure = "user"`, the full p x p target
#'   correlation matrix.  For `"exchangeable"` or `"ar1"`, a single
#'   correlation value in (-1, 1).  Unused for `"block"`.
#' @param structure One of `"user"` (default), `"exchangeable"`, `"ar1"`,
#'   or `"block"`.
#' @param block_sizes Integer vector of block sizes summing to
#'   `length(target_aucs)`.  Required when `structure = "block"`.
#' @param rho_within,rho_between Within- and between-block correlations.
#'   Required when `structure = "block"`.
#' @param feasibility `"error"` (default) or `"nearest"`.  When the
#'   requested p x p correlation matrix is not positive definite, `"error"`
#'   stops with a structured `aucmat_infeasible_targets` condition;
#'   `"nearest"` projects to the nearest positive-semidefinite matrix and
#'   proceeds, reporting the adjustment.
#' @param seed Optional integer seed.
#' @param verify Logical.  If `TRUE` (default), empirically verify achieved
#'   AUCs and correlations on the generated sample.
#'
#' @return An object of class `aucmat_simulation`, a list with components
#'   `data`, `target_aucs`, `achieved_aucs`, `requested_correlation`,
#'   `achieved_correlation`, `mean_shift`, `Sigma`, `feasibility`, `n`,
#'   `prevalence`, `seed`.  `achieved_correlation` is the **within-class**
#'   correlation (each class centred on its own empirical mean before
#'   correlating), matching the scope of `requested_correlation`.  The raw
#'   pooled correlation of `data$X1, data$X2, ...` (ignoring `truth`) will
#'   be systematically higher whenever the corresponding AUCs are above
#'   0.5, because mixing two subpopulations with different means inflates
#'   pooled correlation independently of the within-class dependence
#'   structure.
#'
#' @export
#' @importFrom stats qnorm
#' @examples
#' \donttest{
#' set.seed(1)
#' sim <- simulate_auc_matrix(
#'   n = 500, prevalence = 0.3,
#'   target_aucs = c(0.9, 0.8, 0.7, 0.65),
#'   correlation = 0.4, structure = "exchangeable"
#' )
#' data.frame(target = sim$target_aucs, achieved = round(sim$achieved_aucs, 3))
#' }
simulate_auc_matrix <- function(n = NULL, prevalence = NULL,
                                 y = NULL, positive = NULL,
                                 outcome_mode = c("exact", "bernoulli"),
                                 target_aucs,
                                 correlation = NULL,
                                 structure = c("user", "exchangeable",
                                               "ar1", "block"),
                                 block_sizes = NULL,
                                 rho_within = NULL, rho_between = NULL,
                                 feasibility = c("error", "nearest"),
                                 seed = NULL,
                                 verify = TRUE) {

  outcome_mode <- match.arg(outcome_mode)
  structure    <- match.arg(structure)
  feasibility  <- match.arg(feasibility)

  # ---- 1. Resolve outcome mode ----
  supplied_outcome <- !is.null(y)
  generated_outcome <- !is.null(n) || !is.null(prevalence)

  if (supplied_outcome && generated_outcome) {
    stop("Supply either `y` (and optionally `positive`) or `n`/`prevalence`, ",
         "not both.")
  }
  if (!supplied_outcome && !generated_outcome) {
    stop("Supply either `y` or both `n` and `prevalence`.")
  }

  # ---- 2. Validate target_aucs ----
  if (!is.numeric(target_aucs) || length(target_aucs) < 1L ||
      any(is.na(target_aucs)) || any(target_aucs <= 0 | target_aucs >= 1)) {
    stop("target_aucs must be a numeric vector with all values in (0, 1).")
  }
  p <- length(target_aucs)

  # ---- 3. Build the target correlation matrix (deterministic) ----
  R <- .build_correlation_matrix(
    p, structure, correlation = correlation,
    block_sizes = block_sizes,
    rho_within = rho_within, rho_between = rho_between
  )

  # ---- 4. Feasibility check on R (deterministic, no RNG involved) ----
  proj <- .nearest_pd_correlation(R)

  if (isTRUE(proj$adjusted) && feasibility == "error") {
    msg <- sprintf(paste0(
      "The requested %d x %d correlation matrix is not positive definite ",
      "(minimum eigenvalue = %.6g).  Use feasibility = 'nearest' to ",
      "project to the closest valid matrix, or relax `correlation` / ",
      "`structure`."),
      p, p, proj$min_eigenvalue
    )
    stop(aucmat_infeasible_targets(msg))
  }

  feasibility_info <- list(
    status = if (proj$adjusted) "adjusted" else "ok",
    adjusted = proj$adjusted,
    min_eigenvalue = proj$min_eigenvalue,
    frobenius_adjustment = proj$frobenius_adjustment,
    max_abs_adjustment = proj$max_abs_adjustment
  )
  R_used <- proj$matrix

  with_seed(seed, .simulate_auc_matrix_body(
    R = R, R_used = R_used, p = p, target_aucs = target_aucs,
    supplied_outcome = supplied_outcome,
    y = y, positive = positive,
    n = n, prevalence = prevalence, outcome_mode = outcome_mode,
    feasibility_info = feasibility_info, seed = seed, verify = verify
  ))
}

#' @noRd
#' @keywords internal
.simulate_auc_matrix_body <- function(R, R_used, p, target_aucs,
                                       supplied_outcome, y, positive,
                                       n, prevalence, outcome_mode,
                                       feasibility_info, seed, verify) {

  # ---- 5. Resolve / generate the outcome (fixed BEFORE any biomarker) ----
  if (supplied_outcome) {
    y_norm <- .normalize_binary_y(y, positive)
    n_obs <- length(y_norm)
  } else {
    if (!is.numeric(n) || length(n) != 1L || n < 2L)
      stop("n must be a single integer >= 2.")
    if (!is.numeric(prevalence) || length(prevalence) != 1L ||
        is.na(prevalence) || prevalence <= 0 || prevalence >= 1)
      stop("prevalence must be a single value in (0, 1).")

    n_obs <- as.integer(n)
    if (outcome_mode == "exact") {
      n_pos <- round(n_obs * prevalence)
      n_pos <- max(1L, min(n_obs - 1L, n_pos))
      y_raw <- sample(c(rep(1L, n_pos), rep(0L, n_obs - n_pos)))
    } else {
      y_raw <- stats::rbinom(n_obs, size = 1, prob = prevalence)
      if (sum(y_raw) < 1L || sum(y_raw == 0L) < 1L) {
        stop("Bernoulli draw produced a single-class outcome; ",
             "retry with a different seed or use outcome_mode = 'exact'.")
      }
    }
    y_norm <- factor(y_raw, levels = c(0, 1), labels = c("neg", "pos"))
  }

  pos <- y_norm == levels(y_norm)[2L]
  neg <- !pos
  n_pos <- sum(pos)
  n_neg <- sum(neg)
  prevalence_used <- n_pos / n_obs

  if (n_pos < 2L || n_neg < 2L) {
    stop(aucmat_insufficient_sample(
      "At least 2 observations per class are required to generate biomarkers."
    ))
  }

  # ---- 6. Closed-form binormal mean shift per biomarker ----
  # delta_j = sqrt(2) * qnorm(target_auc_j); centred so the n-weighted
  # mean is 0, matching generate_data_analytical()'s centring.
  delta <- sqrt(2) * stats::qnorm(target_aucs)
  mu0 <- delta * (-n_pos / n_obs)
  mu1 <- delta * ( n_neg / n_obs)

  # ---- 7. Draw class-conditional biomarkers ----
  X_mat <- matrix(NA_real_, n_obs, p)
  X_mat[pos, ] <- mvtnorm::rmvnorm(n_pos, mu1, R_used)
  X_mat[neg, ] <- mvtnorm::rmvnorm(n_neg, mu0, R_used)

  # Per-column standardisation: a monotone affine transform, so it cannot
  # change AUC (rank-invariant) and cannot change Pearson correlation
  # (scale/location-invariant); it only gives the returned columns a
  # conventional (near) unit marginal scale.
  X_mat <- scale(X_mat)
  colnames(X_mat) <- paste0("X", seq_len(p))

  data_df <- as.data.frame(X_mat)
  data_df$truth <- as.integer(pos)

  # ---- 8. Verify ----
  if (isTRUE(verify)) {
    achieved_aucs <- vapply(seq_len(p), function(j) {
      .compute_single_auc(data_df[[j]], pos, neg)$auc_raw
    }, numeric(1L))

    # `requested_correlation` (R) is the WITHIN-class correlation shared by
    # both MVN(mu1, R) and MVN(mu0, R).  The raw pooled sample correlation
    # of X_mat is NOT a consistent estimate of R whenever any AUC != 0.5:
    # mixing two subpopulations with different means systematically
    # inflates the pooled correlation (a mixture/Simpson's-paradox effect;
    # e.g. AUCs of 0.85/0.75 with R = 0.4 inflate the naive pooled
    # correlation to ~0.53).  Centring each class on its own empirical
    # mean before computing correlation removes this contamination and
    # correctly estimates R.
    X_centered <- X_mat
    X_centered[pos, ] <- sweep(X_mat[pos, , drop = FALSE], 2,
                              colMeans(X_mat[pos, , drop = FALSE]), "-")
    X_centered[neg, ] <- sweep(X_mat[neg, , drop = FALSE], 2,
                              colMeans(X_mat[neg, , drop = FALSE]), "-")
    achieved_correlation <- stats::cor(X_centered)
  } else {
    achieved_aucs <- rep(NA_real_, p)
    achieved_correlation <- matrix(NA_real_, p, p)
  }

  out <- list(
    data                  = data_df,
    target_aucs           = target_aucs,
    achieved_aucs         = stats::setNames(achieved_aucs, colnames(X_mat)),
    requested_correlation = R,
    achieved_correlation  = achieved_correlation,
    mean_shift            = stats::setNames(delta, colnames(X_mat)),
    Sigma                 = R_used,
    feasibility           = feasibility_info,
    n = n_obs, prevalence = prevalence_used,
    seed = seed
  )
  class(out) <- "aucmat_simulation"
  out
}
